### ISSUE TITLE
ShaguTweaks_cache and ShaguPlates_playerDB

### ISSUE THREAD

**Issue by geojak** [shagu/ShaguPlates#28]
shagu tweaks and shaguplates both use slighyl different versons of the libunitscan.lua
both files keep a permanet saved table of all players with name, level, class, (and guild for plates). over the run of 3 years playing these two files have grown to an humongous size on my end. i only just found out about it and cleared it up manually for now. i believe this can cause crashes and fps drops when the tables has reached absurd size.

i propose to either
1. make shaguplates use the table of tweaks if both installed
2. consider making 
ShaguPlates_playerDB and ShaguTweaks_cache not permanently saved but instead reset on every login

**Comment by shagu** [comment]
ShaguTweaks uses it to color names in chat and to have nameplate healthbars class colored.
pfUI uses it to have chat colors, last login data on friendlist, healthbar class colors, and probably more than I can remember.
ShaguPlates is just a renamed (by script) pfUI_playerDB that uses it for class colored healthbars only.

I know the table can get big. But I have never had crashes or fps drops due to it.

1. I don't know if this would even work properly to have 3 addons using the same SavedVariable. Also this gets very prone to compatibility issues. If hitting the table max-size of Lua is the only concern, then this solution wouldn't change anything. As already mentioned, performance or crash wise I couldn't trigger anything.

2. Is a clear no. I don't want to lose all chat colors, last login data on friendlist, healthbar colors on each /rl, relog or logout.
If you personally want that, you can just remove it from the SavedVariables of the .toc file.

4. Would be a cleanup job, that automatically removes old data: Which involes saving additional data (a timestamp) and a background job that always scans and clears old values. But at that point, it **really** does something on the performance. And as I couldn't find an impact of the table size as of now, I will not going to do that.
