### ISSUE TITLE
Enemy castbar disappearing when using SuperWoW

### ISSUE THREAD

**Issue by Trust-WoW** [shagu/ShaguPlates#29]
Enemy castbars disappear when I attack the mob. It's not even an interrupt, simply attacking them makes the castbar disappear both on nameplates and the enemy unit frame.

This only happens while using SuperWoW. 
I disabled ShaguPlates and instead used SuperAPI_Castlib with the default nameplates. There everything works as intended with SuperWoW active.

When having ShaguPlates (and its castbar) active, while also having SuperAPI_Castlib active, I can see both castbars at the same time. ShaguPlates castbar will disappear as described above, while SuperAPI_Castlib will remain shown.

Edit: tried it with https://github.com/brotalnia/BlizzPlates, where the castbar works fine with SuperWoW active. But I don't want to use that one, just checked it for testing the issue.

**Comment by shagu** [comment]
It's now fixed via: https://github.com/shagu/pfUI/commit/641476c1bc3dae8bb57040499b0f091bf1fa44a1
ShaguPlates is updated to the latest version via: https://github.com/shagu/ShaguPlates/commit/2c39aac405be002ba901c26582bb8e8a34078c0f

> Edit: tried it with https://github.com/brotalnia/BlizzPlates, where the castbar works fine with SuperWoW active. But I don't want to use that one, just checked it for testing the issue.

Ofc it does, because it doesn't make use of SuperWoW at all. You see all the castbars of all the mobs with the same name, and they never disappear. Same as with ShaguPlates when SuperWoW could not be detected :smile:

**Comment by Trust-WoW** [comment]
Just tested it and can confirm this works as intended now :). Thanks!
